This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./protocole_experimental.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file protocole_experimental.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (15 comparisons).
Generating output file protocole_experimental.acr....done (13 lines written, 0 warnings).
Output written in protocole_experimental.acr.
Transcript written in protocole_experimental.alg.
